// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlcgen

import (
	"context"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (id, account_id, name, token_hash, token_prefix, expires_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, account_id, name, token_hash, token_prefix, last_used_at, expires_at, revoked_at, created_at, updated_at
`

type CreateAPITokenParams struct {
	ID          string
	AccountID   string
	Name        string
	TokenHash   string
	TokenPrefix string
	ExpiresAt   *string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, name, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, name, disabled_at, created_at, updated_at
`

type CreateAccountParams struct {
	ID        string
	Name      string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, disabled_at, created_at, updated_at FROM accounts WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByName = `-- name: GetAccountByName :one
SELECT id, name, disabled_at, created_at, updated_at FROM accounts WHERE name = ?
`

// Names are unique, so this is how the bootstrap seeding tells "already seeded"
// from "seed it now" without ever creating a second account (spec 0004, AC-1).
func (q *Queries) GetAccountByName(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByName, name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (id, account_id, action, target_type, target_id, outcome, reason, occurred_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	ID         string
	AccountID  *string
	Action     string
	TargetType *string
	TargetID   *string
	Outcome    string
	Reason     *string
	OccurredAt string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.ID,
		arg.AccountID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Outcome,
		arg.Reason,
		arg.OccurredAt,
	)
	return err
}

const resolveToken = `-- name: ResolveToken :one
SELECT accounts.id, accounts.name, accounts.disabled_at, accounts.created_at, accounts.updated_at, api_tokens.id, api_tokens.account_id, api_tokens.name, api_tokens.token_hash, api_tokens.token_prefix, api_tokens.last_used_at, api_tokens.expires_at, api_tokens.revoked_at, api_tokens.created_at, api_tokens.updated_at
FROM api_tokens
JOIN accounts ON accounts.id = api_tokens.account_id
WHERE api_tokens.token_hash = ?1
  AND api_tokens.revoked_at IS NULL
  AND (api_tokens.expires_at IS NULL OR api_tokens.expires_at > ?2)
  AND accounts.disabled_at IS NULL
`

type ResolveTokenParams struct {
	TokenHash string
	Now       *string
}

type ResolveTokenRow struct {
	Account  Account
	ApiToken ApiToken
}

// A token resolves to an account only while it is live: not revoked, not past
// its expiry, and belonging to an account that is not locked out. Unknown,
// revoked, expired and disabled are all the same empty result to the caller.
func (q *Queries) ResolveToken(ctx context.Context, arg ResolveTokenParams) (ResolveTokenRow, error) {
	row := q.db.QueryRowContext(ctx, resolveToken, arg.TokenHash, arg.Now)
	var i ResolveTokenRow
	err := row.Scan(
		&i.Account.ID,
		&i.Account.Name,
		&i.Account.DisabledAt,
		&i.Account.CreatedAt,
		&i.Account.UpdatedAt,
		&i.ApiToken.ID,
		&i.ApiToken.AccountID,
		&i.ApiToken.Name,
		&i.ApiToken.TokenHash,
		&i.ApiToken.TokenPrefix,
		&i.ApiToken.LastUsedAt,
		&i.ApiToken.ExpiresAt,
		&i.ApiToken.RevokedAt,
		&i.ApiToken.CreatedAt,
		&i.ApiToken.UpdatedAt,
	)
	return i, err
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens
SET revoked_at = ?1, updated_at = ?1
WHERE id = ?2 AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	Now *string
	ID  string
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPIToken, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeTokensNamed = `-- name: RevokeTokensNamed :execrows
UPDATE api_tokens
SET revoked_at = ?1, updated_at = ?1
WHERE account_id = ?2 AND name = ?3 AND revoked_at IS NULL
`

type RevokeTokensNamedParams struct {
	Now       *string
	AccountID string
	Name      string
}

// Revokes every live token an account holds under one name. The bootstrap
// seeding uses it so rotating DEPLOYER_BOOTSTRAP_TOKEN leaves exactly one live
// token rather than two working ones (spec 0004, AC-1).
func (q *Queries) RevokeTokensNamed(ctx context.Context, arg RevokeTokensNamedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeTokensNamed, arg.Now, arg.AccountID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchTokenLastUsed = `-- name: TouchTokenLastUsed :exec
UPDATE api_tokens SET last_used_at = ?1, updated_at = ?1 WHERE id = ?2
`

type TouchTokenLastUsedParams struct {
	Now *string
	ID  string
}

func (q *Queries) TouchTokenLastUsed(ctx context.Context, arg TouchTokenLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchTokenLastUsed, arg.Now, arg.ID)
	return err
}
