// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package sqlcgen

import (
	"context"
)

const clearConfig = `-- name: ClearConfig :exec
DELETE FROM app_config WHERE app_id = ?1
`

// A rollback replaces the whole configuration set from the release snapshot, so
// it clears first and then writes the snapshot's keys, both inside MarkHealthy's
// transaction (spec 0011, AC-13).
func (q *Queries) ClearConfig(ctx context.Context, appID string) error {
	_, err := q.db.ExecContext(ctx, clearConfig, appID)
	return err
}

const countInFlightDeploymentsForApp = `-- name: CountInFlightDeploymentsForApp :one
SELECT COUNT(*) FROM deployments
WHERE app_id = ?1 AND state NOT IN ('healthy', 'failed', 'cancelled')
`

func (q *Queries) CountInFlightDeploymentsForApp(ctx context.Context, appID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInFlightDeploymentsForApp, appID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApp = `-- name: CreateApp :one
INSERT INTO apps (id, account_id, name, slug, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, account_id, name, slug, current_release_id, deleted_at, created_at, updated_at
`

type CreateAppParams struct {
	ID        string
	AccountID string
	Name      string
	Slug      string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRowContext(ctx, createApp,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Slug,
		&i.CurrentReleaseID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApp = `-- name: GetApp :one
SELECT id, account_id, name, slug, current_release_id, deleted_at, created_at, updated_at FROM apps WHERE id = ?1 AND deleted_at IS NULL
`

func (q *Queries) GetApp(ctx context.Context, id string) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Slug,
		&i.CurrentReleaseID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppByName = `-- name: GetAppByName :one
SELECT id, account_id, name, slug, current_release_id, deleted_at, created_at, updated_at FROM apps WHERE account_id = ?1 AND name = ?2 AND deleted_at IS NULL
`

type GetAppByNameParams struct {
	AccountID string
	Name      string
}

// The get or create lookup every deploy starts with: an app is identified by
// its account and the name that account gave it, and the same pair must always
// resolve to the same row so the hostname never moves (spec 0004, AC-4).
func (q *Queries) GetAppByName(ctx context.Context, arg GetAppByNameParams) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByName, arg.AccountID, arg.Name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Slug,
		&i.CurrentReleaseID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppBySlug = `-- name: GetAppBySlug :one
SELECT id, account_id, name, slug, current_release_id, deleted_at, created_at, updated_at FROM apps WHERE slug = ?1 AND deleted_at IS NULL
`

func (q *Queries) GetAppBySlug(ctx context.Context, slug string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppBySlug, slug)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Slug,
		&i.CurrentReleaseID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppSummariesByAccount = `-- name: ListAppSummariesByAccount :many
SELECT
    a.id,
    a.name,
    a.slug,
    a.created_at,
    r.release_number AS serving_release_number,
    d.id AS last_deployment_id,
    d.state AS last_deployment_state,
    d.failure_reason AS last_deployment_reason,
    -- The newest finish, not the newest deployment's finish: a deploy running
    -- right now has no finished_at, and that must not blank out when the app
    -- last actually deployed (AC-6, Value sourcing).
    -- Coalesced rather than cast: a NULL here is "nothing has finished", and an
    -- empty string carries that without a nullable column to unwrap.
    CAST(COALESCE(f.last_finished, '') AS TEXT) AS last_deployed_at
FROM apps a
LEFT JOIN releases r ON r.id = a.current_release_id
LEFT JOIN deployments d ON d.id = (
    SELECT n.id FROM deployments n
    WHERE n.app_id = a.id
    ORDER BY n.created_at DESC, n.id DESC
    LIMIT 1
)
LEFT JOIN (
    SELECT app_id, MAX(finished_at) AS last_finished FROM deployments GROUP BY app_id
) f ON f.app_id = a.id
WHERE a.account_id = ?1 AND a.deleted_at IS NULL
ORDER BY a.id DESC
LIMIT ?2
`

type ListAppSummariesByAccountParams struct {
	AccountID string
	PageLimit int64
}

type ListAppSummariesByAccountRow struct {
	ID                   string
	Name                 string
	Slug                 string
	CreatedAt            string
	ServingReleaseNumber *int64
	LastDeploymentID     *string
	LastDeploymentState  *string
	LastDeploymentReason *string
	LastDeployedAt       string
}

// The whole app listing in one statement: no loop reading each app's newest
// deployment, and no Kubernetes call anywhere near it (spec 0012, AC-8). The
// projection is deliberate the way the release listing's is: no app_config and
// no config_snapshot column is named, so no configuration value enters the
// process at all (AC-7).
//
// serving and last_deployment are read independently, because an app whose last
// deploy failed is usually still serving its previous release (AC-5).
func (q *Queries) ListAppSummariesByAccount(ctx context.Context, arg ListAppSummariesByAccountParams) ([]ListAppSummariesByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppSummariesByAccount, arg.AccountID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppSummariesByAccountRow{}
	for rows.Next() {
		var i ListAppSummariesByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.ServingReleaseNumber,
			&i.LastDeploymentID,
			&i.LastDeploymentState,
			&i.LastDeploymentReason,
			&i.LastDeployedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByAccount = `-- name: ListAppsByAccount :many
SELECT id, account_id, name, slug, current_release_id, deleted_at, created_at, updated_at FROM apps
WHERE account_id = ?1
  AND deleted_at IS NULL
  AND (?2 = '' OR id < ?2)
ORDER BY id DESC
LIMIT ?3
`

type ListAppsByAccountParams struct {
	AccountID string
	Cursor    interface{}
	PageLimit int64
}

// A page of an account's live apps, newest first. The cursor is the last id of
// the previous page; an empty cursor starts at the top.
func (q *Queries) ListAppsByAccount(ctx context.Context, arg ListAppsByAccountParams) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByAccount, arg.AccountID, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Slug,
			&i.CurrentReleaseID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigForDeploy = `-- name: ListConfigForDeploy :many
SELECT key, value, is_secret FROM app_config WHERE app_id = ?1 ORDER BY key
`

type ListConfigForDeployRow struct {
	Key      string
	Value    string
	IsSecret int64
}

// The deploy path, and the release snapshot, are the only readers of secret
// values.
func (q *Queries) ListConfigForDeploy(ctx context.Context, appID string) ([]ListConfigForDeployRow, error) {
	rows, err := q.db.QueryContext(ctx, listConfigForDeploy, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfigForDeployRow{}
	for rows.Next() {
		var i ListConfigForDeployRow
		if err := rows.Scan(&i.Key, &i.Value, &i.IsSecret); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigForResponse = `-- name: ListConfigForResponse :many
SELECT key, is_secret, CASE WHEN is_secret = 1 THEN NULL ELSE value END AS value
FROM app_config
WHERE app_id = ?1
ORDER BY key
`

type ListConfigForResponseRow struct {
	Key      string
	IsSecret int64
	Value    interface{}
}

// Tool responses read configuration through here and only here: a secret key is
// listed with its flag but never with its value.
func (q *Queries) ListConfigForResponse(ctx context.Context, appID string) ([]ListConfigForResponseRow, error) {
	rows, err := q.db.QueryContext(ctx, listConfigForResponse, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfigForResponseRow{}
	for rows.Next() {
		var i ListConfigForResponseRow
		if err := rows.Scan(&i.Key, &i.IsSecret, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveAppSlugs = `-- name: LiveAppSlugs :many
SELECT slug FROM apps WHERE deleted_at IS NULL
`

// Every live app's slug, which is the one read the orphan reaper trusts to
// decide that a namespace owns nothing (spec 0012, AC-24).
func (q *Queries) LiveAppSlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, liveAppSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppCurrentRelease = `-- name: SetAppCurrentRelease :execrows
UPDATE apps SET current_release_id = ?1, updated_at = ?2 WHERE id = ?3
`

type SetAppCurrentReleaseParams struct {
	ReleaseID *string
	Now       string
	ID        string
}

func (q *Queries) SetAppCurrentRelease(ctx context.Context, arg SetAppCurrentReleaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAppCurrentRelease, arg.ReleaseID, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setConfig = `-- name: SetConfig :exec
INSERT INTO app_config (app_id, key, value, is_secret, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?5)
ON CONFLICT (app_id, key) DO UPDATE
SET value = excluded.value, is_secret = excluded.is_secret, updated_at = excluded.updated_at
`

type SetConfigParams struct {
	AppID    string
	Key      string
	Value    string
	IsSecret int64
	Now      string
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) error {
	_, err := q.db.ExecContext(ctx, setConfig,
		arg.AppID,
		arg.Key,
		arg.Value,
		arg.IsSecret,
		arg.Now,
	)
	return err
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS (SELECT 1 FROM apps WHERE slug = ?1)
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteApp = `-- name: SoftDeleteApp :execrows
UPDATE apps
SET deleted_at = ?1, updated_at = ?1
WHERE id = ?2 AND deleted_at IS NULL
`

type SoftDeleteAppParams struct {
	Now *string
	ID  string
}

func (q *Queries) SoftDeleteApp(ctx context.Context, arg SoftDeleteAppParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteApp, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unsetConfig = `-- name: UnsetConfig :execrows
DELETE FROM app_config WHERE app_id = ?1 AND key = ?2
`

type UnsetConfigParams struct {
	AppID string
	Key   string
}

func (q *Queries) UnsetConfig(ctx context.Context, arg UnsetConfigParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unsetConfig, arg.AppID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
