// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backups.sql

package sqlcgen

import (
	"context"
)

const finishBackupRunFailed = `-- name: FinishBackupRunFailed :execrows
UPDATE backup_runs
SET outcome        = 'failed',
    finished_at    = ?1,
    failure_reason = ?2
WHERE id = ?3 AND outcome = 'running'
`

type FinishBackupRunFailedParams struct {
	FinishedAt    *string
	FailureReason *string
	ID            string
}

func (q *Queries) FinishBackupRunFailed(ctx context.Context, arg FinishBackupRunFailedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishBackupRunFailed, arg.FinishedAt, arg.FailureReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishBackupRunSucceeded = `-- name: FinishBackupRunSucceeded :execrows
UPDATE backup_runs
SET outcome     = 'succeeded',
    finished_at = ?1,
    object_key  = ?2,
    size_bytes  = ?3,
    checksum    = ?4
WHERE id = ?5 AND outcome = 'running'
`

type FinishBackupRunSucceededParams struct {
	FinishedAt *string
	ObjectKey  *string
	SizeBytes  *int64
	Checksum   *string
	ID         string
}

func (q *Queries) FinishBackupRunSucceeded(ctx context.Context, arg FinishBackupRunSucceededParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishBackupRunSucceeded,
		arg.FinishedAt,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.Checksum,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRunningBackupRun = `-- name: GetRunningBackupRun :one
SELECT id, started_at, finished_at, outcome, object_key, size_bytes, checksum, failure_reason, "trigger", triggered_by FROM backup_runs WHERE outcome = 'running'
`

// The read the ticker makes before it attempts anything, so a scheduled tick
// skips rather than vanishing into a swallowed constraint error (AC-12a).
func (q *Queries) GetRunningBackupRun(ctx context.Context) (BackupRun, error) {
	row := q.db.QueryRowContext(ctx, getRunningBackupRun)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Outcome,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Checksum,
		&i.FailureReason,
		&i.Trigger,
		&i.TriggeredBy,
	)
	return i, err
}

const insertBackupRun = `-- name: InsertBackupRun :one

INSERT INTO backup_runs (id, started_at, outcome, trigger, triggered_by)
VALUES (?1, ?2, 'running', ?3, ?4)
RETURNING id, started_at, finished_at, outcome, object_key, size_bytes, checksum, failure_reason, "trigger", triggered_by
`

type InsertBackupRunParams struct {
	ID          string
	StartedAt   string
	Trigger     string
	TriggeredBy *string
}

// Spec 0020. The record of every backup run.
//
// The insert carries no in flight check of its own. The partial unique index
// backup_runs_one_in_flight refuses a second running row, so concurrency is
// decided by the database rather than by a read the caller ran first (AC-8).
//
// Every ending update carries `AND outcome = 'running'` so a terminal row can
// never be rewritten, which is the same shape the deployment transitions use.
func (q *Queries) InsertBackupRun(ctx context.Context, arg InsertBackupRunParams) (BackupRun, error) {
	row := q.db.QueryRowContext(ctx, insertBackupRun,
		arg.ID,
		arg.StartedAt,
		arg.Trigger,
		arg.TriggeredBy,
	)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Outcome,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Checksum,
		&i.FailureReason,
		&i.Trigger,
		&i.TriggeredBy,
	)
	return i, err
}

const latestSucceededBackupRun = `-- name: LatestSucceededBackupRun :one
SELECT id, started_at, finished_at, outcome, object_key, size_bytes, checksum, failure_reason, "trigger", triggered_by FROM backup_runs
WHERE outcome = 'succeeded'
ORDER BY started_at DESC
LIMIT 1
`

// What the startup catch up compares against the interval (AC-12).
func (q *Queries) LatestSucceededBackupRun(ctx context.Context) (BackupRun, error) {
	row := q.db.QueryRowContext(ctx, latestSucceededBackupRun)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Outcome,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Checksum,
		&i.FailureReason,
		&i.Trigger,
		&i.TriggeredBy,
	)
	return i, err
}

const latestTerminalBackupRun = `-- name: LatestTerminalBackupRun :one
SELECT id, started_at, finished_at, outcome, object_key, size_bytes, checksum, failure_reason, "trigger", triggered_by FROM backup_runs
WHERE outcome IN ('succeeded', 'failed')
ORDER BY started_at DESC
LIMIT 1
`

// The previous terminal run, read before the current row is written, which is
// what decides whether a success is a recovery (AC-13).
func (q *Queries) LatestTerminalBackupRun(ctx context.Context) (BackupRun, error) {
	row := q.db.QueryRowContext(ctx, latestTerminalBackupRun)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Outcome,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Checksum,
		&i.FailureReason,
		&i.Trigger,
		&i.TriggeredBy,
	)
	return i, err
}

const listBackupRuns = `-- name: ListBackupRuns :many
SELECT id, started_at, finished_at, outcome, object_key, size_bytes, checksum, failure_reason, "trigger", triggered_by FROM backup_runs
ORDER BY started_at DESC
LIMIT ?1
`

func (q *Queries) ListBackupRuns(ctx context.Context, lim int64) ([]BackupRun, error) {
	rows, err := q.db.QueryContext(ctx, listBackupRuns, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupRun{}
	for rows.Next() {
		var i BackupRun
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Outcome,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.Checksum,
			&i.FailureReason,
			&i.Trigger,
			&i.TriggeredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const strandRunningBackupRuns = `-- name: StrandRunningBackupRuns :execrows
UPDATE backup_runs
SET outcome        = 'failed',
    finished_at    = ?1,
    failure_reason = ?2
WHERE outcome = 'running'
`

type StrandRunningBackupRunsParams struct {
	FinishedAt    *string
	FailureReason *string
}

// The startup sweep. One replica and a Recreate strategy make a running row
// definitionally dead, so this ends every one of them without a grace period
// (AC-9).
func (q *Queries) StrandRunningBackupRuns(ctx context.Context, arg StrandRunningBackupRunsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, strandRunningBackupRuns, arg.FinishedAt, arg.FailureReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
