// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package sqlcgen

import (
	"context"
)

const claimNextDeployment = `-- name: ClaimNextDeployment :one
UPDATE deployments
SET claimed_at = ?1, claimed_by = ?2, updated_at = ?1
WHERE id = (
    SELECT id FROM deployments
    WHERE state = 'queued' AND claimed_at IS NULL
    ORDER BY id
    LIMIT 1
)
AND claimed_at IS NULL
RETURNING id, app_id, account_id, upload_id, source_release_id, state, build_path, build_job_name, image_repo, image_digest, failure_reason, claimed_at, claimed_by, started_at, finished_at, created_at, updated_at
`

type ClaimNextDeploymentParams struct {
	Now       *string
	ClaimedBy *string
}

// One claim wins. The inner select picks the oldest unclaimed queued row and the
// outer WHERE re-checks the claim, so a racing caller updates zero rows.
func (q *Queries) ClaimNextDeployment(ctx context.Context, arg ClaimNextDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, claimNextDeployment, arg.Now, arg.ClaimedBy)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.UploadID,
		&i.SourceReleaseID,
		&i.State,
		&i.BuildPath,
		&i.BuildJobName,
		&i.ImageRepo,
		&i.ImageDigest,
		&i.FailureReason,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (id, app_id, account_id, upload_id, source_release_id, state, image_digest, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'queued', ?, ?, ?)
RETURNING id, app_id, account_id, upload_id, source_release_id, state, build_path, build_job_name, image_repo, image_digest, failure_reason, claimed_at, claimed_by, started_at, finished_at, created_at, updated_at
`

type CreateDeploymentParams struct {
	ID              string
	AppID           string
	AccountID       string
	UploadID        *string
	SourceReleaseID *string
	ImageDigest     *string
	CreatedAt       string
	UpdatedAt       string
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.ID,
		arg.AppID,
		arg.AccountID,
		arg.UploadID,
		arg.SourceReleaseID,
		arg.ImageDigest,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.UploadID,
		&i.SourceReleaseID,
		&i.State,
		&i.BuildPath,
		&i.BuildJobName,
		&i.ImageRepo,
		&i.ImageDigest,
		&i.FailureReason,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, app_id, account_id, upload_id, source_release_id, state, build_path, build_job_name, image_repo, image_digest, failure_reason, claimed_at, claimed_by, started_at, finished_at, created_at, updated_at FROM deployments WHERE id = ?
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.UploadID,
		&i.SourceReleaseID,
		&i.State,
		&i.BuildPath,
		&i.BuildJobName,
		&i.ImageRepo,
		&i.ImageDigest,
		&i.FailureReason,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInFlightDeploymentForApp = `-- name: GetInFlightDeploymentForApp :one
SELECT id, app_id, account_id, upload_id, source_release_id, state, build_path, build_job_name, image_repo, image_digest, failure_reason, claimed_at, claimed_by, started_at, finished_at, created_at, updated_at FROM deployments
WHERE app_id = ?1 AND state NOT IN ('healthy', 'failed', 'cancelled')
`

func (q *Queries) GetInFlightDeploymentForApp(ctx context.Context, appID string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getInFlightDeploymentForApp, appID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.UploadID,
		&i.SourceReleaseID,
		&i.State,
		&i.BuildPath,
		&i.BuildJobName,
		&i.ImageRepo,
		&i.ImageDigest,
		&i.FailureReason,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelease = `-- name: GetRelease :one
SELECT id, app_id, deployment_id, release_number, image_digest, config_snapshot, created_at FROM releases WHERE id = ?
`

func (q *Queries) GetRelease(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRowContext(ctx, getRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.DeploymentID,
		&i.ReleaseNumber,
		&i.ImageDigest,
		&i.ConfigSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getReleaseByDeployment = `-- name: GetReleaseByDeployment :one
SELECT id, app_id, deployment_id, release_number, image_digest, config_snapshot, created_at FROM releases WHERE deployment_id = ?1
`

// The release a deployment minted, which is what a successful deploy reports
// back rather than recomputing the number or the digest.
func (q *Queries) GetReleaseByDeployment(ctx context.Context, deploymentID string) (Release, error) {
	row := q.db.QueryRowContext(ctx, getReleaseByDeployment, deploymentID)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.DeploymentID,
		&i.ReleaseNumber,
		&i.ImageDigest,
		&i.ConfigSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const insertDeploymentEvent = `-- name: InsertDeploymentEvent :exec
INSERT INTO deployment_events (id, deployment_id, from_state, to_state, reason, detail, occurred_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertDeploymentEventParams struct {
	ID           string
	DeploymentID string
	FromState    *string
	ToState      string
	Reason       *string
	Detail       *string
	OccurredAt   string
}

func (q *Queries) InsertDeploymentEvent(ctx context.Context, arg InsertDeploymentEventParams) error {
	_, err := q.db.ExecContext(ctx, insertDeploymentEvent,
		arg.ID,
		arg.DeploymentID,
		arg.FromState,
		arg.ToState,
		arg.Reason,
		arg.Detail,
		arg.OccurredAt,
	)
	return err
}

const insertRelease = `-- name: InsertRelease :one
INSERT INTO releases (id, app_id, deployment_id, release_number, image_digest, config_snapshot, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, app_id, deployment_id, release_number, image_digest, config_snapshot, created_at
`

type InsertReleaseParams struct {
	ID             string
	AppID          string
	DeploymentID   string
	ReleaseNumber  int64
	ImageDigest    string
	ConfigSnapshot string
	CreatedAt      string
}

func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, insertRelease,
		arg.ID,
		arg.AppID,
		arg.DeploymentID,
		arg.ReleaseNumber,
		arg.ImageDigest,
		arg.ConfigSnapshot,
		arg.CreatedAt,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.DeploymentID,
		&i.ReleaseNumber,
		&i.ImageDigest,
		&i.ConfigSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploymentEvents = `-- name: ListDeploymentEvents :many
SELECT id, deployment_id, from_state, to_state, reason, detail, occurred_at FROM deployment_events
WHERE deployment_id = ?1
ORDER BY occurred_at, id
`

func (q *Queries) ListDeploymentEvents(ctx context.Context, deploymentID string) ([]DeploymentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentEvents, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentEvent{}
	for rows.Next() {
		var i DeploymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.FromState,
			&i.ToState,
			&i.Reason,
			&i.Detail,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByApp = `-- name: ListDeploymentsByApp :many
SELECT id, app_id, account_id, upload_id, source_release_id, state, build_path, build_job_name, image_repo, image_digest, failure_reason, claimed_at, claimed_by, started_at, finished_at, created_at, updated_at FROM deployments
WHERE app_id = ?1 AND (?2 = '' OR id < ?2)
ORDER BY id DESC
LIMIT ?3
`

type ListDeploymentsByAppParams struct {
	AppID     string
	Cursor    interface{}
	PageLimit int64
}

func (q *Queries) ListDeploymentsByApp(ctx context.Context, arg ListDeploymentsByAppParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsByApp, arg.AppID, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.AccountID,
			&i.UploadID,
			&i.SourceReleaseID,
			&i.State,
			&i.BuildPath,
			&i.BuildJobName,
			&i.ImageRepo,
			&i.ImageDigest,
			&i.FailureReason,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonTerminalDeployments = `-- name: ListNonTerminalDeployments :many
SELECT id, app_id, account_id, upload_id, source_release_id, state, build_path, build_job_name, image_repo, image_digest, failure_reason, claimed_at, claimed_by, started_at, finished_at, created_at, updated_at FROM deployments
WHERE state NOT IN ('healthy', 'failed', 'cancelled')
ORDER BY id
`

func (q *Queries) ListNonTerminalDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listNonTerminalDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.AccountID,
			&i.UploadID,
			&i.SourceReleaseID,
			&i.State,
			&i.BuildPath,
			&i.BuildJobName,
			&i.ImageRepo,
			&i.ImageDigest,
			&i.FailureReason,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesByApp = `-- name: ListReleasesByApp :many
SELECT id, app_id, deployment_id, release_number, image_digest, config_snapshot, created_at FROM releases
WHERE app_id = ?1 AND (?2 = '' OR id < ?2)
ORDER BY id DESC
LIMIT ?3
`

type ListReleasesByAppParams struct {
	AppID     string
	Cursor    interface{}
	PageLimit int64
}

func (q *Queries) ListReleasesByApp(ctx context.Context, arg ListReleasesByAppParams) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, listReleasesByApp, arg.AppID, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.DeploymentID,
			&i.ReleaseNumber,
			&i.ImageDigest,
			&i.ConfigSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextReleaseNumber = `-- name: NextReleaseNumber :one
SELECT COALESCE(MAX(release_number), 0) + 1 AS next FROM releases WHERE app_id = ?1
`

func (q *Queries) NextReleaseNumber(ctx context.Context, appID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextReleaseNumber, appID)
	var next int64
	err := row.Scan(&next)
	return next, err
}

const recordBuildResult = `-- name: RecordBuildResult :execrows
UPDATE deployments
SET build_path = ?1,
    build_job_name = ?2,
    image_repo = ?3,
    image_digest = ?4,
    updated_at = ?5
WHERE id = ?6
`

type RecordBuildResultParams struct {
	BuildPath    *string
	BuildJobName *string
	ImageRepo    *string
	ImageDigest  *string
	Now          string
	ID           string
}

func (q *Queries) RecordBuildResult(ctx context.Context, arg RecordBuildResultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordBuildResult,
		arg.BuildPath,
		arg.BuildJobName,
		arg.ImageRepo,
		arg.ImageDigest,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDeploymentState = `-- name: UpdateDeploymentState :one
UPDATE deployments
SET state = ?1,
    failure_reason = COALESCE(?2, failure_reason),
    started_at = COALESCE(started_at, ?3),
    finished_at = COALESCE(finished_at, ?4),
    updated_at = ?5
WHERE id = ?6
RETURNING id, app_id, account_id, upload_id, source_release_id, state, build_path, build_job_name, image_repo, image_digest, failure_reason, claimed_at, claimed_by, started_at, finished_at, created_at, updated_at
`

type UpdateDeploymentStateParams struct {
	State         string
	FailureReason *string
	StartedAt     *string
	FinishedAt    *string
	Now           string
	ID            string
}

// The transition writes state and its two lifecycle stamps together. started_at
// and finished_at are only ever set, never cleared, so a null argument leaves
// whatever is already there.
func (q *Queries) UpdateDeploymentState(ctx context.Context, arg UpdateDeploymentStateParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, updateDeploymentState,
		arg.State,
		arg.FailureReason,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Now,
		arg.ID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.UploadID,
		&i.SourceReleaseID,
		&i.State,
		&i.BuildPath,
		&i.BuildJobName,
		&i.ImageRepo,
		&i.ImageDigest,
		&i.FailureReason,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
