// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"
)

const consumeEmailToken = `-- name: ConsumeEmailToken :execrows
UPDATE email_tokens SET consumed_at = ?1 WHERE id = ?2 AND consumed_at IS NULL
`

type ConsumeEmailTokenParams struct {
	Now *string
	ID  string
}

func (q *Queries) ConsumeEmailToken(ctx context.Context, arg ConsumeEmailTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeEmailToken, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeLiveEmailTokens = `-- name: ConsumeLiveEmailTokens :execrows
UPDATE email_tokens SET consumed_at = ?1
WHERE account_id = ?2 AND purpose = ?3 AND consumed_at IS NULL
`

type ConsumeLiveEmailTokensParams struct {
	Now       *string
	AccountID string
	Purpose   string
}

// Supersedes whatever link the account holds for that purpose, so a resend leaves
// exactly one live link rather than two working ones (AC-6).
func (q *Queries) ConsumeLiveEmailTokens(ctx context.Context, arg ConsumeLiveEmailTokensParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeLiveEmailTokens, arg.Now, arg.AccountID, arg.Purpose)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countEmailAccounts = `-- name: CountEmailAccounts :one
SELECT COUNT(*) FROM accounts WHERE email IS NOT NULL
`

// The first admin rule, asked inside the creating transaction. The bootstrap
// account holds a null email, so it never counts as the first (AC-4).
func (q *Queries) CountEmailAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO email_tokens (id, account_id, purpose, token_hash, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id, account_id, purpose, token_hash, expires_at, consumed_at, created_at
`

type CreateEmailTokenParams struct {
	ID        string
	AccountID string
	Purpose   string
	TokenHash string
	ExpiresAt string
	Now       string
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRowContext(ctx, createEmailToken,
		arg.ID,
		arg.AccountID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Now,
	)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createIdentityAccount = `-- name: CreateIdentityAccount :one

INSERT INTO accounts (id, name, email, password_hash, display_name, is_admin, created_at, updated_at)
VALUES (?1, ?1, ?2, ?3, ?4, ?5, ?6, ?6)
RETURNING id, name, disabled_at, created_at, updated_at, email, password_hash, email_verified_at, is_admin, display_name
`

type CreateIdentityAccountParams struct {
	ID           string
	Email        *string
	PasswordHash *string
	DisplayName  *string
	IsAdmin      int64
	Now          string
}

// Spec 0007. The identity half of the account: registration, sessions, single use
// email links, and the token management surface a person drives from a session.
// Registration writes the account's own id into name, so the NOT NULL UNIQUE
// constraint that column was designed with is satisfied by construction and never
// becomes a user visible collision. The human label lives in display_name.
func (q *Queries) CreateIdentityAccount(ctx context.Context, arg CreateIdentityAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createIdentityAccount,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.IsAdmin,
		arg.Now,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DisplayName,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, account_id, token_hash, expires_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?5)
RETURNING id, account_id, token_hash, expires_at, last_used_at, revoked_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID        string
	AccountID string
	TokenHash string
	ExpiresAt string
	Now       string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Now,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, account_id, name, token_hash, token_prefix, last_used_at, expires_at, revoked_at, created_at, updated_at FROM api_tokens WHERE id = ?1
`

func (q *Queries) GetAPIToken(ctx context.Context, id string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPIToken, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, name, disabled_at, created_at, updated_at, email, password_hash, email_verified_at, is_admin, display_name FROM accounts WHERE email = ?1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email *string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.IsAdmin,
		&i.DisplayName,
	)
	return i, err
}

const getLiveEmailToken = `-- name: GetLiveEmailToken :one
SELECT id, account_id, purpose, token_hash, expires_at, consumed_at, created_at FROM email_tokens
WHERE token_hash = ?1
  AND purpose = ?2
  AND consumed_at IS NULL
  AND expires_at > ?3
`

type GetLiveEmailTokenParams struct {
	TokenHash string
	Purpose   string
	Now       string
}

// Matched on the hash and the purpose together, never the hash alone, so a link
// minted to verify an address cannot be spent to reset the password on it (AC-5).
func (q *Queries) GetLiveEmailToken(ctx context.Context, arg GetLiveEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRowContext(ctx, getLiveEmailToken, arg.TokenHash, arg.Purpose, arg.Now)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, disabled_at, created_at, updated_at, email, password_hash, email_verified_at, is_admin, display_name FROM accounts ORDER BY created_at DESC
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.PasswordHash,
			&i.EmailVerifiedAt,
			&i.IsAdmin,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveAPITokens = `-- name: ListLiveAPITokens :many
SELECT id, account_id, name, token_hash, token_prefix, last_used_at, expires_at, revoked_at, created_at, updated_at FROM api_tokens
WHERE account_id = ?1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > ?2)
ORDER BY created_at DESC
`

type ListLiveAPITokensParams struct {
	AccountID string
	Now       *string
}

// No pagination: one live name per account is already enforced, so a token list
// is small by construction (AC-13).
func (q *Queries) ListLiveAPITokens(ctx context.Context, arg ListLiveAPITokensParams) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listLiveAPITokens, arg.AccountID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :execrows
UPDATE accounts SET email_verified_at = ?1, updated_at = ?1
WHERE id = ?2 AND email_verified_at IS NULL
`

type MarkEmailVerifiedParams struct {
	Now *string
	ID  string
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markEmailVerified, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveSession = `-- name: ResolveSession :one
SELECT accounts.id, accounts.name, accounts.disabled_at, accounts.created_at, accounts.updated_at, accounts.email, accounts.password_hash, accounts.email_verified_at, accounts.is_admin, accounts.display_name, sessions.id, sessions.account_id, sessions.token_hash, sessions.expires_at, sessions.last_used_at, sessions.revoked_at, sessions.created_at, sessions.updated_at
FROM sessions
JOIN accounts ON accounts.id = sessions.account_id
WHERE sessions.token_hash = ?1
  AND sessions.revoked_at IS NULL
  AND sessions.expires_at > ?2
  AND accounts.disabled_at IS NULL
`

type ResolveSessionParams struct {
	TokenHash string
	Now       string
}

type ResolveSessionRow struct {
	Account Account
	Session Session
}

// A session resolves only while it is live: not revoked, not past its rolling
// expiry, and belonging to an account that is not locked out. Every failing case
// is the same empty result, exactly as ResolveToken is.
func (q *Queries) ResolveSession(ctx context.Context, arg ResolveSessionParams) (ResolveSessionRow, error) {
	row := q.db.QueryRowContext(ctx, resolveSession, arg.TokenHash, arg.Now)
	var i ResolveSessionRow
	err := row.Scan(
		&i.Account.ID,
		&i.Account.Name,
		&i.Account.DisabledAt,
		&i.Account.CreatedAt,
		&i.Account.UpdatedAt,
		&i.Account.Email,
		&i.Account.PasswordHash,
		&i.Account.EmailVerifiedAt,
		&i.Account.IsAdmin,
		&i.Account.DisplayName,
		&i.Session.ID,
		&i.Session.AccountID,
		&i.Session.TokenHash,
		&i.Session.ExpiresAt,
		&i.Session.LastUsedAt,
		&i.Session.RevokedAt,
		&i.Session.CreatedAt,
		&i.Session.UpdatedAt,
	)
	return i, err
}

const revokeAccountEmailTokens = `-- name: RevokeAccountEmailTokens :execrows
UPDATE email_tokens SET consumed_at = ?1
WHERE account_id = ?2 AND consumed_at IS NULL
`

type RevokeAccountEmailTokensParams struct {
	Now       *string
	AccountID string
}

func (q *Queries) RevokeAccountEmailTokens(ctx context.Context, arg RevokeAccountEmailTokensParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAccountEmailTokens, arg.Now, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeAccountSessions = `-- name: RevokeAccountSessions :execrows
UPDATE sessions SET revoked_at = ?1, updated_at = ?1
WHERE account_id = ?2 AND revoked_at IS NULL
`

type RevokeAccountSessionsParams struct {
	Now       *string
	AccountID string
}

// Used by disable and by a password change, both of which must leave no live
// session behind, in the same transaction as the change itself (AC-10).
func (q *Queries) RevokeAccountSessions(ctx context.Context, arg RevokeAccountSessionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAccountSessions, arg.Now, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions SET revoked_at = ?1, updated_at = ?1 WHERE id = ?2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	Now *string
	ID  string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeSession, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAccountDisabled = `-- name: SetAccountDisabled :execrows
UPDATE accounts SET disabled_at = ?1, updated_at = ?2 WHERE id = ?3
`

type SetAccountDisabledParams struct {
	DisabledAt *string
	Now        string
	ID         string
}

func (q *Queries) SetAccountDisabled(ctx context.Context, arg SetAccountDisabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountDisabled, arg.DisabledAt, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPasswordHash = `-- name: SetPasswordHash :execrows
UPDATE accounts SET password_hash = ?1, updated_at = ?2 WHERE id = ?3
`

type SetPasswordHashParams struct {
	PasswordHash *string
	Now          string
	ID           string
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPasswordHash, arg.PasswordHash, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = ?1, expires_at = ?2, updated_at = ?1 WHERE id = ?3
`

type TouchSessionParams struct {
	Now       *string
	ExpiresAt string
	ID        string
}

// Rolling expiry: every authenticated request pushes the session forward (AC-9).
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.Now, arg.ExpiresAt, arg.ID)
	return err
}
