// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package sqlcgen

import (
	"context"
)

const anyAccountHasEmail = `-- name: AnyAccountHasEmail :one
SELECT EXISTS (SELECT 1 FROM accounts WHERE email IS NOT NULL)
`

// The two reads the startup bootstrap decides from. Either one being true means
// the platform mints nothing and logs nothing (AC-13).
func (q *Queries) AnyAccountHasEmail(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, anyAccountHasEmail)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const anyLiveBootstrapInvite = `-- name: AnyLiveBootstrapInvite :one
SELECT EXISTS (
    SELECT 1 FROM invites
    WHERE created_by IS NULL
      AND consumed_at IS NULL
      AND revoked_at IS NULL
      AND expires_at > ?1
)
`

func (q *Queries) AnyLiveBootstrapInvite(ctx context.Context, now string) (bool, error) {
	row := q.db.QueryRowContext(ctx, anyLiveBootstrapInvite, now)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createInvite = `-- name: CreateInvite :one

INSERT INTO invites (id, code_hash, note, created_by, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id, code_hash, note, created_by, expires_at, consumed_at, consumed_by, revoked_at, created_at
`

type CreateInviteParams struct {
	ID        string
	CodeHash  string
	Note      *string
	CreatedBy *string
	ExpiresAt string
	Now       string
}

// Spec 0015. The invite that authorises a registration.
//
// Every lookup carries the live predicate in full, without exception:
// consumed_at IS NULL AND revoked_at IS NULL AND expires_at > now. The spend
// guard and the revoke guard both carry all three clauses, so neither can act on
// a row the other has already ended (AC-4, AC-5, AC-7).
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.ID,
		arg.CodeHash,
		arg.Note,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.Now,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Note,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT i.id, i.note, i.expires_at, i.consumed_at, i.revoked_at, i.created_at,
       issuer.display_name AS issuer_name,
       spender.email       AS spender_email
FROM invites i
LEFT JOIN accounts issuer  ON issuer.id  = i.created_by
LEFT JOIN accounts spender ON spender.id = i.consumed_by
ORDER BY i.created_at DESC
`

type ListInvitesRow struct {
	ID           string
	Note         *string
	ExpiresAt    string
	ConsumedAt   *string
	RevokedAt    *string
	CreatedAt    string
	IssuerName   *string
	SpenderEmail *string
}

// The admin list, newest first, with the two names it displays resolved here
// rather than by a read per row. The code hash is in the row type and never
// reaches a page: the layer above projects it away (AC-8).
func (q *Queries) ListInvites(ctx context.Context) ([]ListInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesRow{}
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Note,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.IssuerName,
			&i.SpenderEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveInviteByCodeHash = `-- name: LiveInviteByCodeHash :one
SELECT id, code_hash, note, created_by, expires_at, consumed_at, consumed_by, revoked_at, created_at FROM invites
WHERE code_hash = ?1
  AND consumed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > ?2
`

type LiveInviteByCodeHashParams struct {
	CodeHash string
	Now      string
}

// The lookup registration makes before it does any other work. A code that is
// unknown, spent, revoked or expired is the same empty result, so the caller
// cannot tell which kind of bad code they hold (AC-2).
func (q *Queries) LiveInviteByCodeHash(ctx context.Context, arg LiveInviteByCodeHashParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, liveInviteByCodeHash, arg.CodeHash, arg.Now)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Note,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE invites SET revoked_at = ?1
WHERE id = ?2
  AND consumed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > ?1
`

type RevokeInviteParams struct {
	Now *string
	ID  string
}

// Revoking carries the same guard, so revoking an invite that is already spent
// or expired touches nothing and is refused not_found (AC-7).
func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeInvite, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const spendInvite = `-- name: SpendInvite :execrows
UPDATE invites SET consumed_at = ?1, consumed_by = ?2
WHERE id = ?3
  AND consumed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > ?1
`

type SpendInviteParams struct {
	Now        *string
	ConsumedBy *string
	ID         string
}

// Spending is a conditional update returning a row count, run inside the same
// transaction as the account insert. The predicate is the full live one, so
// nothing rests on the earlier lookup still being true by the time this runs:
// two registrations racing on one code end with exactly one account (AC-4).
func (q *Queries) SpendInvite(ctx context.Context, arg SpendInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, spendInvite, arg.Now, arg.ConsumedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
