// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type Account struct {
	ID              string
	Name            string
	DisabledAt      *string
	CreatedAt       string
	UpdatedAt       string
	Email           *string
	PasswordHash    *string
	EmailVerifiedAt *string
	IsAdmin         int64
	DisplayName     *string
	ConnectedAt     *string
}

type ApiToken struct {
	ID            string
	AccountID     string
	Name          string
	TokenHash     string
	TokenPrefix   string
	LastUsedAt    *string
	ExpiresAt     *string
	RevokedAt     *string
	CreatedAt     string
	UpdatedAt     string
	OauthClientID *string
}

type App struct {
	ID               string
	AccountID        string
	Name             string
	Slug             string
	CurrentReleaseID *string
	DeletedAt        *string
	CreatedAt        string
	UpdatedAt        string
}

type AppConfig struct {
	AppID     string
	Key       string
	Value     string
	IsSecret  int64
	CreatedAt string
	UpdatedAt string
}

type AuditLog struct {
	ID            string
	AccountID     *string
	Action        string
	TargetType    *string
	TargetID      *string
	Outcome       string
	Reason        *string
	OccurredAt    string
	ClientAddress *string
}

type BackupRun struct {
	ID            string
	StartedAt     string
	FinishedAt    *string
	Outcome       string
	ObjectKey     *string
	SizeBytes     *int64
	Checksum      *string
	FailureReason *string
	Trigger       string
	TriggeredBy   *string
}

type Deployment struct {
	ID              string
	AppID           string
	AccountID       string
	UploadID        *string
	SourceReleaseID *string
	State           string
	BuildPath       *string
	BuildJobName    *string
	ImageRepo       *string
	ImageDigest     *string
	FailureReason   *string
	ClaimedAt       *string
	ClaimedBy       *string
	StartedAt       *string
	FinishedAt      *string
	CreatedAt       string
	UpdatedAt       string
}

type DeploymentEvent struct {
	ID           string
	DeploymentID string
	FromState    *string
	ToState      string
	Reason       *string
	Detail       *string
	OccurredAt   string
}

type EmailToken struct {
	ID         string
	AccountID  string
	Purpose    string
	TokenHash  string
	ExpiresAt  string
	ConsumedAt *string
	CreatedAt  string
}

type Invite struct {
	ID         string
	CodeHash   string
	Note       *string
	CreatedBy  *string
	ExpiresAt  string
	ConsumedAt *string
	ConsumedBy *string
	RevokedAt  *string
	CreatedAt  string
	Email      *string
}

type OauthClient struct {
	ID           string
	Name         string
	RedirectUris string
	CreatedAt    string
	ApprovedAt   *string
}

type OauthCode struct {
	CodeHash      string
	ClientID      string
	AccountID     string
	RedirectUri   string
	CodeChallenge string
	Resource      string
	TokenID       *string
	ExpiresAt     string
	ConsumedAt    *string
	CreatedAt     string
}

type Release struct {
	ID             string
	AppID          string
	DeploymentID   string
	ReleaseNumber  int64
	ImageDigest    string
	ConfigSnapshot string
	CreatedAt      string
}

type Session struct {
	ID         string
	AccountID  string
	TokenHash  string
	ExpiresAt  string
	LastUsedAt *string
	RevokedAt  *string
	CreatedAt  string
	UpdatedAt  string
}

type Upload struct {
	ID             string
	AccountID      string
	Path           string
	SizeBytes      int64
	Sha256         string
	FetchTokenHash string
	RedeemedAt     *string
	ExpiresAt      string
	CreatedAt      string
	UpdatedAt      string
}
