// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package sqlcgen

import (
	"context"
)

const approveOAuthClient = `-- name: ApproveOAuthClient :execrows
UPDATE oauth_clients SET approved_at = ?1
WHERE id = ?2 AND approved_at IS NULL
`

type ApproveOAuthClientParams struct {
	Now *string
	ID  string
}

// Stamping a client approved is one conditional statement rather than a read
// followed by a write, the same shape MarkAccountConnected uses. A second
// approval by anyone matches no row, changes nothing, and is not an error:
// approved_at records that some account once approved this client, never which.
func (q *Queries) ApproveOAuthClient(ctx context.Context, arg ApproveOAuthClientParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, approveOAuthClient, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeOAuthCode = `-- name: ConsumeOAuthCode :one
UPDATE oauth_codes SET consumed_at = ?1
WHERE code_hash = ?2 AND consumed_at IS NULL AND expires_at > ?1
RETURNING code_hash, client_id, account_id, redirect_uri, code_challenge, resource, token_id, expires_at, consumed_at, created_at
`

type ConsumeOAuthCodeParams struct {
	Now      *string
	CodeHash string
}

// Spending a code is one conditional statement and only a row count of one
// proceeds to mint (AC-18a). A read followed by a write would let two token
// requests arriving together both see the code unconsumed and both mint from
// it. The expiry is part of the same condition, so an expired code is spent by
// nobody.
func (q *Queries) ConsumeOAuthCode(ctx context.Context, arg ConsumeOAuthCodeParams) (OauthCode, error) {
	row := q.db.QueryRowContext(ctx, consumeOAuthCode, arg.Now, arg.CodeHash)
	var i OauthCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.AccountID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.Resource,
		&i.TokenID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createClientAPIToken = `-- name: CreateClientAPIToken :one
INSERT INTO api_tokens (id, account_id, name, token_hash, token_prefix, oauth_client_id, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?7)
RETURNING id, account_id, name, token_hash, token_prefix, last_used_at, expires_at, revoked_at, created_at, updated_at, oauth_client_id
`

type CreateClientAPITokenParams struct {
	ID            string
	AccountID     string
	Name          string
	TokenHash     string
	TokenPrefix   string
	OauthClientID *string
	Now           string
}

func (q *Queries) CreateClientAPIToken(ctx context.Context, arg CreateClientAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createClientAPIToken,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.OauthClientID,
		arg.Now,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthClientID,
	)
	return i, err
}

const createOAuthClient = `-- name: CreateOAuthClient :one

INSERT INTO oauth_clients (id, name, redirect_uris, created_at)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, name, redirect_uris, created_at, approved_at
`

type CreateOAuthClientParams struct {
	ID           string
	Name         string
	RedirectUris string
	Now          string
}

// Spec 0024. The authorization server's own rows: the clients a stranger may
// register, the codes an approval issues, and the grant that turns one into an
// ordinary api_tokens row.
func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, createOAuthClient,
		arg.ID,
		arg.Name,
		arg.RedirectUris,
		arg.Now,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RedirectUris,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const createOAuthCode = `-- name: CreateOAuthCode :one
INSERT INTO oauth_codes (code_hash, client_id, account_id, redirect_uri, code_challenge, resource, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
RETURNING code_hash, client_id, account_id, redirect_uri, code_challenge, resource, token_id, expires_at, consumed_at, created_at
`

type CreateOAuthCodeParams struct {
	CodeHash      string
	ClientID      string
	AccountID     string
	RedirectUri   string
	CodeChallenge string
	Resource      string
	ExpiresAt     string
	Now           string
}

func (q *Queries) CreateOAuthCode(ctx context.Context, arg CreateOAuthCodeParams) (OauthCode, error) {
	row := q.db.QueryRowContext(ctx, createOAuthCode,
		arg.CodeHash,
		arg.ClientID,
		arg.AccountID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.Resource,
		arg.ExpiresAt,
		arg.Now,
	)
	var i OauthCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.AccountID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.Resource,
		&i.TokenID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUnapprovedOAuthClients = `-- name: DeleteUnapprovedOAuthClients :execrows
DELETE FROM oauth_clients
WHERE approved_at IS NULL AND created_at < ?1
`

// The daily sweep (AC-8). A client nobody ever approved is a row a stranger
// created, so it dies once the resumable window passes. A stamped row is never
// touched here. Deleting a client cascades its codes.
func (q *Queries) DeleteUnapprovedOAuthClients(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnapprovedOAuthClients, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, name, redirect_uris, created_at, approved_at FROM oauth_clients WHERE id = ?1
`

func (q *Queries) GetOAuthClient(ctx context.Context, id string) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, getOAuthClient, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RedirectUris,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const getOAuthCode = `-- name: GetOAuthCode :one
SELECT code_hash, client_id, account_id, redirect_uri, code_challenge, resource, token_id, expires_at, consumed_at, created_at FROM oauth_codes WHERE code_hash = ?1
`

// Read for the replay case only (AC-16a): a code that is already consumed still
// has to be found, so the token it issued can be revoked. The exchange itself
// never reads first, it consumes.
func (q *Queries) GetOAuthCode(ctx context.Context, codeHash string) (OauthCode, error) {
	row := q.db.QueryRowContext(ctx, getOAuthCode, codeHash)
	var i OauthCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.AccountID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.Resource,
		&i.TokenID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeLiveClientTokens = `-- name: RevokeLiveClientTokens :execrows
UPDATE api_tokens
SET revoked_at = ?1, updated_at = ?1
WHERE account_id = ?2 AND oauth_client_id = ?3 AND revoked_at IS NULL
`

type RevokeLiveClientTokensParams struct {
	Now           *string
	AccountID     string
	OauthClientID *string
}

// Revokes every live token this account already holds for this client, so the
// partial unique index never sees two. Runs in the same transaction as the mint
// that replaces it (AC-19a, AC-19b).
func (q *Queries) RevokeLiveClientTokens(ctx context.Context, arg RevokeLiveClientTokensParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeLiveClientTokens, arg.Now, arg.AccountID, arg.OauthClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setOAuthCodeToken = `-- name: SetOAuthCodeToken :execrows
UPDATE oauth_codes SET token_id = ?1 WHERE code_hash = ?2
`

type SetOAuthCodeTokenParams struct {
	TokenID  *string
	CodeHash string
}

func (q *Queries) SetOAuthCodeToken(ctx context.Context, arg SetOAuthCodeTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setOAuthCodeToken, arg.TokenID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
