// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package sqlcgen

import (
	"context"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (id, account_id, path, size_bytes, sha256, fetch_token_hash, expires_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, account_id, path, size_bytes, sha256, fetch_token_hash, redeemed_at, expires_at, created_at, updated_at
`

type CreateUploadParams struct {
	ID             string
	AccountID      string
	Path           string
	SizeBytes      int64
	Sha256         string
	FetchTokenHash string
	ExpiresAt      string
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRowContext(ctx, createUpload,
		arg.ID,
		arg.AccountID,
		arg.Path,
		arg.SizeBytes,
		arg.Sha256,
		arg.FetchTokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Path,
		&i.SizeBytes,
		&i.Sha256,
		&i.FetchTokenHash,
		&i.RedeemedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgedEvents = `-- name: DeleteAgedEvents :execrows
DELETE FROM deployment_events WHERE occurred_at < ?1
`

func (q *Queries) DeleteAgedEvents(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgedEvents, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEventsOfSweptDeployments = `-- name: DeleteEventsOfSweptDeployments :execrows
DELETE FROM deployment_events
WHERE deployment_id IN (
    SELECT id FROM deployments
    WHERE state IN ('failed', 'cancelled')
      AND finished_at IS NOT NULL
      AND finished_at < ?1
)
`

func (q *Queries) DeleteEventsOfSweptDeployments(ctx context.Context, cutoff *string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEventsOfSweptDeployments, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteStaleUploads = `-- name: DeleteStaleUploads :execrows
DELETE FROM uploads
WHERE uploads.created_at < ?1
  AND (redeemed_at IS NOT NULL OR expires_at < ?2)
  AND id NOT IN (SELECT upload_id FROM deployments WHERE upload_id IS NOT NULL)
`

type DeleteStaleUploadsParams struct {
	UploadCutoff string
	Now          string
}

// An upload still named by a surviving deployment stays: nothing cascades, so
// the sweep has to leave the parent's children intact.
func (q *Queries) DeleteStaleUploads(ctx context.Context, arg DeleteStaleUploadsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStaleUploads, arg.UploadCutoff, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSweptDeployments = `-- name: DeleteSweptDeployments :execrows
DELETE FROM deployments
WHERE state IN ('failed', 'cancelled')
  AND finished_at IS NOT NULL
  AND finished_at < ?1
`

func (q *Queries) DeleteSweptDeployments(ctx context.Context, cutoff *string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSweptDeployments, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUpload = `-- name: GetUpload :one
SELECT id, account_id, path, size_bytes, sha256, fetch_token_hash, redeemed_at, expires_at, created_at, updated_at FROM uploads WHERE id = ?
`

func (q *Queries) GetUpload(ctx context.Context, id string) (Upload, error) {
	row := q.db.QueryRowContext(ctx, getUpload, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Path,
		&i.SizeBytes,
		&i.Sha256,
		&i.FetchTokenHash,
		&i.RedeemedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const redeemUpload = `-- name: RedeemUpload :one
UPDATE uploads
SET redeemed_at = ?1, updated_at = ?1
WHERE fetch_token_hash = ?2
  AND redeemed_at IS NULL
  AND expires_at > ?1
RETURNING id, account_id, path, size_bytes, sha256, fetch_token_hash, redeemed_at, expires_at, created_at, updated_at
`

type RedeemUploadParams struct {
	Now            *string
	FetchTokenHash string
}

// Single use, enforced by the update itself rather than a read then a write:
// zero rows back means the token was already spent or has expired.
func (q *Queries) RedeemUpload(ctx context.Context, arg RedeemUploadParams) (Upload, error) {
	row := q.db.QueryRowContext(ctx, redeemUpload, arg.Now, arg.FetchTokenHash)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Path,
		&i.SizeBytes,
		&i.Sha256,
		&i.FetchTokenHash,
		&i.RedeemedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
