---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deployer-mail
  namespace: deployer-system
spec:
  encryptedData:
    DEPLOYER_RESEND_API_KEY: AgA7ots0V+XjjV9PTOeBTSc7DHdFskzFEc3hfpt+WBGgyXl9/V2WG+VTpkl0cqZPeGIzkUq1efYp+1UYgtJNj223T84X4uPiN9G1Sr3tKQxnCQQtyJTftrQJcoyggyzydTVuMcZX2nSz4UYKrPKd2aOohcY5qQY51Rdn2I5NieqZJEZ97i93/MdrUFHSh2Yc6s7NThug/BpZm5B3cevOXVulhn0p90PW7fc1V0fCzOO2+izI9nkc1ovmXoDIPRmHnhBwHsYmlaNzZ1TojyBso3qwc/9JaFMtCnn2mtjczFsWUmSk7hJfgyILz14MboUeIIgrct9DXkMlx1Q3HaLKcO/qxfO4YE6CowLT9nEXfEh8aK4S60hgyQ4FLClogrKjC+Z3nPTWubwDTTApNdby3funrSIoKcXshVsjnditBi0+A6+RpJmaqEthHr4+SHwgYs0R6w0zUkioWbO5T04C3x7TE8vNQtJ4qqzczXBL1X0g2Zh5LEvdGwHEfOXlEPxNi1iIuZQmuTtoLB5qLf6VSby7kjsTeY/pqSBakaSS2bnfR7N3aC8rjdptcZjAIehnR/0x/u4SjFVs4yrFxJuiodeHX2IhaErXTYOF4ft/hR9+Q3oidXIvPIKGpIxBEzEnaxJUOpi5mQq/oyUsOm4OsLO+YonoWUGtC/TEcp9jTVdMtLg0AavW9iNZggSsDzCLjYSB9aSrX/P/559OjoNinfEyqvj5Njwgc2BRrLdFEOaDGXF5y0U=
  template:
    metadata:
      name: deployer-mail
      namespace: deployer-system
