---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deployer-registry-htpasswd
  namespace: deployer-system
spec:
  encryptedData:
    htpasswd: AgC79PUbEic+MUXD4+IR9RTnDxC5BmZfdAW7AxJhIG7xnT9l3K8MVPKA9n8qgncbg/46louw6CAUzRg3aGUH6BhQ5vsaz872+GAEMwjKNpHBnRqWA6RZ8eNaA2hsD8T1fR5fFqQw3QfOnOxlQ4DplMr5u1AYsfK9mKs3Ow7grHXi+eHxT/E/U+pEd9hSEGd1xikhPcAnTOJ/K3muvY+3JhVzyR2jnnIvvw2pgLj7JWaVRkOP3t0KGPWD8QbVmz0ykf9oCmKP9oBufEIxUtcm/0bmI9Fx2p9CtFtuD6zmcf7RsKR715dkEosSclyK1ENadh1eJqhDPRrAnD2f6LuY9tOpPMjSLhBdYHQ+6rWuietmnt8rzxdHbjYCJRVHfMRDdxt7YJ3HpxWUx4oNaQGf+4oc6xDuVqDKsNU7PhDcnVFXyAibWGoWavDZn1TLXm/SW/6PJQF0uMTaS0g450apSTlSNL/aX2NNX95SeB4f6WyKRdQo32zZL8Z3uiTt+MsvQX8cXa0jhEbDLb2CLvRhyMSFeGJpDgzUGQLD+fWboHbeo/oNz/EFL1xGnRyhcY4IdaQN17i5O6tUHIeAEA345X+MjhakTe8CkjB/m/gleO+xP/n4jANYjrcC4Yxck/TCtne02Vj2WQcsA5RGs0HKIuRsIgI56WyvBnyG1udx5f0Qy1ZpztLvArWP1GITjQe+d787qKxdvWi42VuPgmE3HKM67RoH1rYRQ9aGf1QyQotpg5/yo/KaHya4ot1HEH5xMRSmdguigpfoepcXyJmuqQKHToSmTVILJQ==
  template:
    metadata:
      name: deployer-registry-htpasswd
      namespace: deployer-system
